## Task1

In [4]:
import numpy as np

In [7]:
# Creating a 1d and 2d array
arr1 = np.arange(1,11)
arr2 = np.arange(1,10).reshape((3,3))
numArr = np.array([10,20,30,40,50])
print(arr1)
print(arr2)
print(numArr)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30 40 50]


In [10]:
# Shape and dtype
print(arr1.shape, arr2.shape, numArr.shape)
print(arr1.dtype, arr2.dtype, numArr.dtype)

(10,) (3, 3) (5,)
int32 int32 int32


## Task2

In [16]:
A = np.array([1,2,3,4])
B = np.array([10,20,30,40])

print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A**2)

#extra
print(np.add(A,B), np.subtract(A,B))

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[ 1  4  9 16]
[11 22 33 44] [ -9 -18 -27 -36]


## Task3

In [21]:
values = np.array([2,4,6,8,10])

print(f" the square root is: {np.sqrt(values)}")
print(f" the Exponential is: {np.exp(values)}")
print(f" the Log is: {np.log(values)}")
print(f" the Sum is: {np.sum(values)}")
print(f" the Cumalative sum is: {np.cumsum(values)}")

 the square root is: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
 the Exponential is: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
 the Log is: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
 the Sum is: 30
 the Cumalative sum is: [ 2  6 12 20 30]


## Task4

In [25]:
data = np.arange(10,100,10).reshape((3,3))
print(f"The row wise sum is: {np.sum(data, axis=1)}")
print(f"The Column wise sum is: {np.sum(data, axis=0)}")
print(f"The Maximum is: {np.max(data)}")
print(f"The minimum is: {np.min(data)}")
print(f"The mean is: {np.mean(data)}")

The row wise sum is: [ 60 150 240]
The Column wise sum is: [120 150 180]
The Maximum is: 90
The minimum is: 10
The mean is: 50.0


## Task5

In [26]:
marks = np.array([78,85,90,66,72,88,95,60])

print(f"Mean of marks is: {np.mean(marks)}")
print(f"Median of marks is: {np.median(marks)}")
print(f"Variance of marks is: {np.var(marks)}")
print(f"SD of marks is: {np.std(marks)}")
print(f"Min of marks is: {np.min(marks)}")
print(f"Max of marks is: {np.max(marks)}")
print(f"Range of marks is: {np.max(marks) - np.min(marks)}")

Mean of marks is: 79.25
Median of marks is: 81.5
Variance of marks is: 134.1875
SD of marks is: 11.583932838203095
Min of marks is: 60
Max of marks is: 95
Range of marks is: 35


## Task6

In [36]:
marks = np.sort(marks)

print(f"25th percentile: {np.percentile(marks, 25)}")
print(f"50th percentile: {np.percentile(marks, 50)}")
print(f"75th percentile: {np.percentile(marks, 75)}")
above_avg_students = marks > np.mean(marks)
print(f"No. of students above avg: {np.sum(above_avg_students)}")

25th percentile: 70.5
50th percentile: 81.5
75th percentile: 88.5
No. of students above avg: 4


## Task7

In [45]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

print(f"Total weekly sales: {np.sum(sales)}")
print(f"Avg daily sale: {np.mean(sales)}")
print(f"Highest sale is {np.max(sales)} and lowest sale is {np.min(sales)}")
print(f"SD of sales data is: {np.std(sales)}")

above_avg_sales = sales > np.mean(sales)
index_for_above_avg_sales = np.where(above_avg_sales)
print(f"The days when sales is above avg are: {index_for_above_avg_sales}")

Total weekly sales: 10700
Avg daily sale: 1528.5714285714287
Highest sale is 2000 and lowest sale is 900
SD of sales data is: 345.2298849598449
The days when sales is above avg are: (array([3, 4, 5, 6], dtype=int64),)
